### ISSUE TITLE
deploy:assets:backup_manifest fails

### ISSUE THREAD

**Issue by Tietew** [capistrano/rails#111]
after bundle update, deploy:assets:backup_manifest fails with following error:
```
INFO [0c385440] Running /usr/bin/env cp /home/path/to/production/releases/2015****/public/assets/manifest* /home/path/to/production/releases/2015****/assets_manifest_backup as ****@****.jp
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as ****@****.jp: cp exit status: 1
cp stdout: Nothing written
cp stderr: cp: cannot stat ‘/home/path/to/production/releases/2015****/public/assets/manifest*’: No such file or directory
```

The filename of manifest seems to be renamed to `.sprockets-manifest-(random).json`

The change is maybe https://github.com/rails/sprockets/commit/ce6508e8540f829c6221afa39fdf718e4dded096
included since sprockets 3.0.0.

**Comment by benjaminsigidi** [comment]
:+1:

**Comment by kirs** [comment]
What is the Rails version you use? I assume you have Sprockets 3.0.0.

**Comment by benjaminsigidi** [comment]
@kirs yes sprockets (3.0.0)

**Comment by kirs** [comment]
Please, read my question carefully.

**Comment by Tietew** [comment]
@kirs rails 4.2.1 & sprockets 3.0.0

Adding `gem 'sprockets', '~> 2.8'` to Gemfile is workaround to avoid this issue.

**Comment by benjaminsigidi** [comment]
@Tietew Thanks for the work around. Managed to deploy.

**Comment by kirs** [comment]
Thanks for the report. I will work on the fix ASAP.

**Comment by krsyoung** [comment]
Thanks @Tietew, bailed me out of a bind this AM!

**Comment by baburdick** [comment]
+1

Same issue. Workaround does it for me.

**Comment by montdidier** [comment]
+1 same issue here.

**Comment by kirs** [comment]
BTW I tried to upgrade my app on Sprockets 3.0, but I noticed some showstoppering issues: https://github.com/reactjs/react-rails/issues/240, https://github.com/emberjs/ember-rails/issues/469. I would suggest to wait before the upgrade until it will be stable.

I pushed the possible fix to branch called `sprockets-3`.
You can try it with: `gem 'capistrano-rails', github: 'capistrano/rails', branch: 'sprockets-3'`
Please, report if it works (including `rollback`)
@montdidier @baburdick @krsyoung @Tietew

**Comment by tatat** [comment]
@kirs there is a syntax error

```
SyntaxError: /Users/ta/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/rails-e8ad7eddc10c/lib/capistrano/tasks/assets.rake:73: syntax error, unexpected tIDENTIFIER, expecting ')'
          new_manifest = capture(:ls, base_path, '....
                      ^
/Users/ta/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/rails-e8ad7eddc10c/lib/capistrano/tasks/assets.rake:73: syntax error, unexpected ')', expecting keyword_end
...path, '.sprockets-manifest-*')).strip
...                               ^
/Users/ta/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/rails-e8ad7eddc10c/lib/capistrano/tasks/assets.rake:90: syntax error, unexpected tIDENTIFIER, expecting ')'
          new_manifest = capture(:ls, base_path.joi...
                      ^
```

**Comment by betesh** [comment]
@kirs I put together my own solution to this before realizing there's an open ticket for it already.  Once I realized, I referenced the ticket in my commit.  In my opinion, my commit is more optimal, since the 2 tasks (`backup_manifest` and `restore_manifest`) share code instead of duplicating it.

**Comment by chussenot** [comment]
```
$ cap deploy
(Backtrace restricted to imported tasks)
cap aborted!
SyntaxError: /Users/chussenot/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-e8ad7eddc10c/lib/capistrano/tasks/assets.rake:73: syntax error, unexpected tIDENTIFIER, expecting ')'
          new_manifest = capture(:ls, base_path, '....
                      ^
/Users/chussenot/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-e8ad7eddc10c/lib/capistrano/tasks/assets.rake:73: syntax error, unexpected ')', expecting keyword_end
...path, '.sprockets-manifest-*')).strip
...                               ^
/Users/chussenot/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rails-e8ad7eddc10c/lib/capistrano/tasks/assets.rake:90: syntax error, unexpected tIDENTIFIER, expecting ')'
          new_manifest = capture(:ls, base_path.joi...
                      ^
/Users/chussenot/Sites/platform/Capfile:22:in `require'
/Users/chussenot/Sites/platform/Capfile:22:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by betesh** [comment]
@chussenot Does my PR work for you?

**Comment by Tietew** [comment]
@kirs deploy works after 2 fixes (see https://github.com/capistrano/rails/compare/sprockets-3...Tietew:sprockets-3) -- but rollback failed.
deploy seems also fail with sprockets < 3.0 because `ls .sprockets-manifest*` will fail.

Failed log belows:
```
DEBUG [5311da92] Running /usr/bin/env ls /home/***/releases/20150415041341/public/assets/.sprockets-manifest-* as ***@***.jp
DEBUG [5311da92] Command: cd /home/***/releases/20150415041341 && ( RBENV_ROOT=/usr/local/rbenv RBENV_VERSION=2.2.2 /usr/bin/env ls /home/***/releases/20150415041341/public/assets/.sprockets-manifest-* )
DEBUG [5311da92]        /home/***/releases/20150415041341/public/assets/.sprockets-manifest-b93aabbf4844125525f01edf849a1740.json
DEBUG [5311da92] Finished in 0.016 seconds with exit status 0 (successful).
DEBUG [6421905c] Running /usr/bin/env ls /home/***/releases/20150415041341/public/assets/manifest* as ***@***.jp
DEBUG [6421905c] Command: cd /home/***/releases/20150415041341 && ( RBENV_ROOT=/usr/local/rbenv RBENV_VERSION=2.2.2 /usr/bin/env ls /home/***/releases/20150415041341/public/assets/manifest* )
DEBUG [6421905c]        ls: cannot access /home/***/releases/20150415041341/public/assets/manifest*: No such file or directory
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as ***@***.jp: ls exit status: 2
ls stdout: Nothing written
ls stderr: ls: cannot access /home/***/releases/20150415041341/public/assets/manifest*: No such file or directory
```

**Comment by kirs** [comment]
@Tietew thanks!
We will work on @betesh's PR today (https://github.com/capistrano/rails/pull/112)

**Comment by chulkilee** [comment]
#115 will fix it

**Comment by emirkin** [comment]
Possibly related:

When I do the first `cap production deploy`, `rake assets:precompile` goes through my assets and then does: `'....../releases/20150415154907/public/assets/manifest*’: No such file or directory`

I tried fixing it by `cap production deploy:compile_assets` as suggested by http://stackoverflow.com/questions/27121502/rails-4-capistrano-3-deploy-error-public-assets-manifest-no-such-file-or-dire, but that broke on `/current` directory not being found (the link hasn't been created yet)

**Comment by i5okie** [comment]
Just installed capistrano-rails from repo.. did ```cap production bundler:install```
still getting the error.. (let me know if I should try something else)
```console
% cap production deploy:compile_assets                                                                                                                                           1 ↵
DEBUG [ad68961a] Running /usr/bin/env if test ! -d /home/deploy/app/current; then echo "Directory does not exist '/home/deploy/app/current'" 1>&2; false; fi as deploy@11.22.33.44
DEBUG [ad68961a] Command: if test ! -d /home/deploy/app/current; then echo "Directory does not exist '/home/deploy/app/current'" 1>&2; false; fi
DEBUG [ad68961a] Finished in 1.949 seconds with exit status 0 (successful).
INFO [a12c88b3] Running /usr/local/bin/chruby-exec 2.2.1 -- bundle exec rake assets:precompile as deploy@11.22.33.44
DEBUG [a12c88b3] Command: cd /home/deploy/app/current && ( RAILS_ENV=production /usr/local/bin/chruby-exec 2.2.1 -- bundle exec rake assets:precompile )
INFO [a12c88b3] Finished in 4.545 seconds with exit status 0 (successful).
DEBUG [94c2a268] Running /usr/bin/env if test ! -d /home/deploy/app/current; then echo "Directory does not exist '/home/deploy/app/current'" 1>&2; false; fi as deploy@11.22.33.44
DEBUG [94c2a268] Command: if test ! -d /home/deploy/app/current; then echo "Directory does not exist '/home/deploy/app/current'" 1>&2; false; fi
DEBUG [94c2a268] Finished in 0.172 seconds with exit status 0 (successful).
INFO [2220505b] Running /usr/bin/env cp /home/deploy/app/current/public/assets/manifest* /home/deploy/app/current/assets_manifest_backup as deploy@11.22.33.44
DEBUG [2220505b] Command: cd /home/deploy/app/current && /usr/bin/env cp /home/deploy/app/current/public/assets/manifest* /home/deploy/app/current/assets_manifest_backup
INFO [2220505b] Finished in 0.177 seconds with exit status 0 (successful).
[ivan@Ivans-MBP:~/GitHub/app on master]
% cap production deploy
INFO [d91025c0] Running /usr/bin/env mkdir -p /tmp/app/ as deploy@11.22.33.44
DEBUG [d91025c0] Command: /usr/bin/env mkdir -p /tmp/app/
INFO [d91025c0] Finished in 1.847 seconds with exit status 0 (successful).
DEBUG Uploading /tmp/app/git-ssh.sh 0.0%
INFO Uploading /tmp/app/git-ssh.sh 100.0%
INFO [cbe01221] Running /usr/bin/env chmod +x /tmp/app/git-ssh.sh as deploy@11.22.33.44
DEBUG [cbe01221] Command: /usr/bin/env chmod +x /tmp/app/git-ssh.sh
INFO [cbe01221] Finished in 0.180 seconds with exit status 0 (successful).
INFO [6dea5143] Running /usr/bin/env git ls-remote --heads git@github.com:i5okie/app.git as deploy@11.22.33.44
DEBUG [6dea5143] Command: ( GIT_ASKPASS=/bin/echo GIT_SSH=/tmp/app/git-ssh.sh /usr/bin/env git ls-remote --heads git@github.com:i5okie/app.git )
DEBUG [6dea5143] 	78f205ceeee876f16115ce655245e6f13a0c914b	refs/heads/cap/stages
DEBUG [6dea5143] 	b22b7c5e99ab44116e15aefa7608add057a7fd69	refs/heads/master
DEBUG [6dea5143] 	35864056f5adb5f6ea3f6fb9d5435174e8a2e38f	refs/heads/vagrant
INFO [6dea5143] Finished in 0.563 seconds with exit status 0 (successful).
INFO [c77a2a69] Running /usr/bin/env mkdir -p /home/deploy/app/shared /home/deploy/app/releases as deploy@11.22.33.44
DEBUG [c77a2a69] Command: /usr/bin/env mkdir -p /home/deploy/app/shared /home/deploy/app/releases
INFO [c77a2a69] Finished in 0.178 seconds with exit status 0 (successful).
INFO [aaf32702] Running /usr/bin/env mkdir -p /home/deploy/app/shared/bin /home/deploy/app/shared/log /home/deploy/app/shared/tmp/pids /home/deploy/app/shared/tmp/cache /home/deploy/app/shared/tmp/sockets /home/deploy/app/shared/vendor/bundle /home/deploy/app/shared/public/system as deploy@11.22.33.44
DEBUG [aaf32702] Command: /usr/bin/env mkdir -p /home/deploy/app/shared/bin /home/deploy/app/shared/log /home/deploy/app/shared/tmp/pids /home/deploy/app/shared/tmp/cache /home/deploy/app/shared/tmp/sockets /home/deploy/app/shared/vendor/bundle /home/deploy/app/shared/public/system
INFO [aaf32702] Finished in 0.190 seconds with exit status 0 (successful).
INFO [9480e077] Running /usr/bin/env mkdir -p /home/deploy/app/shared/config as deploy@11.22.33.44
DEBUG [9480e077] Command: /usr/bin/env mkdir -p /home/deploy/app/shared/config
INFO [9480e077] Finished in 0.180 seconds with exit status 0 (successful).
DEBUG [ac388f72] Running /usr/bin/env [ -f /home/deploy/app/shared/config/application.yml ] as deploy@11.22.33.44
DEBUG [ac388f72] Command: [ -f /home/deploy/app/shared/config/application.yml ]
DEBUG [ac388f72] Finished in 0.176 seconds with exit status 0 (successful).
DEBUG [5311fd3a] Running /usr/bin/env [ -f /home/deploy/app/current/REVISION ] as deploy@11.22.33.44
DEBUG [5311fd3a] Command: [ -f /home/deploy/app/current/REVISION ]
DEBUG [5311fd3a] Finished in 0.177 seconds with exit status 0 (successful).
DEBUG [7b099853] Running /usr/bin/env cat /home/deploy/app/current/REVISION 2>/dev/null as deploy@11.22.33.44
DEBUG [7b099853] Command: /usr/bin/env cat /home/deploy/app/current/REVISION 2>/dev/null
DEBUG [7b099853] 	14c4e63
DEBUG [7b099853] Finished in 0.187 seconds with exit status 0 (successful).
DEBUG [fa123a83] Running /usr/bin/env [ -f /home/deploy/app/repo/HEAD ] as deploy@11.22.33.44
DEBUG [fa123a83] Command: [ -f /home/deploy/app/repo/HEAD ]
DEBUG [fa123a83] Finished in 0.173 seconds with exit status 0 (successful).
INFO The repository mirror is at /home/deploy/app/repo
DEBUG [5b24207a] Running /usr/bin/env if test ! -d /home/deploy/app/repo; then echo "Directory does not exist '/home/deploy/app/repo'" 1>&2; false; fi as deploy@11.22.33.44
DEBUG [5b24207a] Command: if test ! -d /home/deploy/app/repo; then echo "Directory does not exist '/home/deploy/app/repo'" 1>&2; false; fi
DEBUG [5b24207a] Finished in 0.177 seconds with exit status 0 (successful).
INFO [1157d3f0] Running /usr/bin/env git remote update as deploy@11.22.33.44
DEBUG [1157d3f0] Command: cd /home/deploy/app/repo && ( GIT_ASKPASS=/bin/echo GIT_SSH=/tmp/app/git-ssh.sh /usr/bin/env git remote update )
DEBUG [1157d3f0] 	Fetching origin
INFO [1157d3f0] Finished in 0.587 seconds with exit status 0 (successful).
DEBUG [fe3c21ff] Running /usr/bin/env if test ! -d /home/deploy/app/repo; then echo "Directory does not exist '/home/deploy/app/repo'" 1>&2; false; fi as deploy@11.22.33.44
DEBUG [fe3c21ff] Command: if test ! -d /home/deploy/app/repo; then echo "Directory does not exist '/home/deploy/app/repo'" 1>&2; false; fi
DEBUG [fe3c21ff] Finished in 0.175 seconds with exit status 0 (successful).
INFO [a1ea01bd] Running /usr/bin/env mkdir -p /home/deploy/app/releases/20150416231543 as deploy@11.22.33.44
DEBUG [a1ea01bd] Command: cd /home/deploy/app/repo && ( GIT_ASKPASS=/bin/echo GIT_SSH=/tmp/app/git-ssh.sh /usr/bin/env mkdir -p /home/deploy/app/releases/20150416231543 )
INFO [a1ea01bd] Finished in 0.193 seconds with exit status 0 (successful).
INFO [31e6300f] Running /usr/bin/env git archive master | tar -x -f - -C /home/deploy/app/releases/20150416231543 as deploy@11.22.33.44
DEBUG [31e6300f] Command: cd /home/deploy/app/repo && ( GIT_ASKPASS=/bin/echo GIT_SSH=/tmp/app/git-ssh.sh /usr/bin/env git archive master | tar -x -f - -C /home/deploy/app/releases/20150416231543 )
INFO [31e6300f] Finished in 0.660 seconds with exit status 0 (successful).
DEBUG [4589839d] Running /usr/bin/env if test ! -d /home/deploy/app/repo; then echo "Directory does not exist '/home/deploy/app/repo'" 1>&2; false; fi as deploy@11.22.33.44
DEBUG [4589839d] Command: if test ! -d /home/deploy/app/repo; then echo "Directory does not exist '/home/deploy/app/repo'" 1>&2; false; fi
DEBUG [4589839d] Finished in 0.182 seconds with exit status 0 (successful).
DEBUG [5618beef] Running /usr/bin/env git rev-list --max-count=1 --abbrev-commit master as deploy@11.22.33.44
DEBUG [5618beef] Command: cd /home/deploy/app/repo && ( GIT_ASKPASS=/bin/echo GIT_SSH=/tmp/app/git-ssh.sh /usr/bin/env git rev-list --max-count=1 --abbrev-commit master )
DEBUG [5618beef] 	b22b7c5
DEBUG [5618beef] Finished in 0.181 seconds with exit status 0 (successful).
DEBUG [9b002601] Running /usr/bin/env if test ! -d /home/deploy/app/releases/20150416231543; then echo "Directory does not exist '/home/deploy/app/releases/20150416231543'" 1>&2; false; fi as deploy@11.22.33.44
DEBUG [9b002601] Command: if test ! -d /home/deploy/app/releases/20150416231543; then echo "Directory does not exist '/home/deploy/app/releases/20150416231543'" 1>&2; false; fi
DEBUG [9b002601] Finished in 0.174 seconds with exit status 0 (successful).
INFO [050a469b] Running /usr/bin/env echo "b22b7c5" >> REVISION as deploy@11.22.33.44
DEBUG [050a469b] Command: cd /home/deploy/app/releases/20150416231543 && /usr/bin/env echo "b22b7c5" >> REVISION
INFO [050a469b] Finished in 0.184 seconds with exit status 0 (successful).
INFO [6db945b3] Running /usr/bin/env mkdir -p /home/deploy/app/releases/20150416231543/config /home/deploy/app/releases/20150416231543/config as deploy@11.22.33.44
DEBUG [6db945b3] Command: /usr/bin/env mkdir -p /home/deploy/app/releases/20150416231543/config /home/deploy/app/releases/20150416231543/config
INFO [6db945b3] Finished in 0.180 seconds with exit status 0 (successful).
DEBUG [6d5c7a83] Running /usr/bin/env [ -L /home/deploy/app/releases/20150416231543/config/application.yml ] as deploy@11.22.33.44
DEBUG [6d5c7a83] Command: [ -L /home/deploy/app/releases/20150416231543/config/application.yml ]
DEBUG [6d5c7a83] Finished in 0.178 seconds with exit status 1 (failed).
DEBUG [a332b794] Running /usr/bin/env [ -f /home/deploy/app/releases/20150416231543/config/application.yml ] as deploy@11.22.33.44
DEBUG [a332b794] Command: [ -f /home/deploy/app/releases/20150416231543/config/application.yml ]
DEBUG [a332b794] Finished in 0.177 seconds with exit status 1 (failed).
INFO [ced29254] Running /usr/bin/env ln -s /home/deploy/app/shared/config/application.yml /home/deploy/app/releases/20150416231543/config/application.yml as deploy@11.22.33.44
DEBUG [ced29254] Command: /usr/bin/env ln -s /home/deploy/app/shared/config/application.yml /home/deploy/app/releases/20150416231543/config/application.yml
INFO [ced29254] Finished in 0.178 seconds with exit status 0 (successful).
DEBUG [1db099fd] Running /usr/bin/env [ -L /home/deploy/app/releases/20150416231543/config/application.yml ] as deploy@11.22.33.44
DEBUG [1db099fd] Command: [ -L /home/deploy/app/releases/20150416231543/config/application.yml ]
DEBUG [1db099fd] Finished in 0.182 seconds with exit status 0 (successful).
INFO [0f3a8cc9] Running /usr/bin/env mkdir -p /home/deploy/app/releases/20150416231543 /home/deploy/app/releases/20150416231543 /home/deploy/app/releases/20150416231543/tmp /home/deploy/app/releases/20150416231543/tmp /home/deploy/app/releases/20150416231543/tmp /home/deploy/app/releases/20150416231543/vendor /home/deploy/app/releases/20150416231543/public as deploy@11.22.33.44
DEBUG [0f3a8cc9] Command: /usr/bin/env mkdir -p /home/deploy/app/releases/20150416231543 /home/deploy/app/releases/20150416231543 /home/deploy/app/releases/20150416231543/tmp /home/deploy/app/releases/20150416231543/tmp /home/deploy/app/releases/20150416231543/tmp /home/deploy/app/releases/20150416231543/vendor /home/deploy/app/releases/20150416231543/public
INFO [0f3a8cc9] Finished in 0.182 seconds with exit status 0 (successful).
DEBUG [e9c0b610] Running /usr/bin/env [ -L /home/deploy/app/releases/20150416231543/bin ] as deploy@11.22.33.44
DEBUG [e9c0b610] Command: [ -L /home/deploy/app/releases/20150416231543/bin ]
DEBUG [e9c0b610] Finished in 0.182 seconds with exit status 1 (failed).
DEBUG [2b333d10] Running /usr/bin/env [ -d /home/deploy/app/releases/20150416231543/bin ] as deploy@11.22.33.44
DEBUG [2b333d10] Command: [ -d /home/deploy/app/releases/20150416231543/bin ]
DEBUG [2b333d10] Finished in 0.187 seconds with exit status 0 (successful).
INFO [1f0fccc9] Running /usr/bin/env rm -rf /home/deploy/app/releases/20150416231543/bin as deploy@11.22.33.44
DEBUG [1f0fccc9] Command: /usr/bin/env rm -rf /home/deploy/app/releases/20150416231543/bin
INFO [1f0fccc9] Finished in 0.181 seconds with exit status 0 (successful).
INFO [380d7339] Running /usr/bin/env ln -s /home/deploy/app/shared/bin /home/deploy/app/releases/20150416231543/bin as deploy@11.22.33.44
DEBUG [380d7339] Command: /usr/bin/env ln -s /home/deploy/app/shared/bin /home/deploy/app/releases/20150416231543/bin
INFO [380d7339] Finished in 0.180 seconds with exit status 0 (successful).
DEBUG [2f06f29a] Running /usr/bin/env [ -L /home/deploy/app/releases/20150416231543/log ] as deploy@11.22.33.44
DEBUG [2f06f29a] Command: [ -L /home/deploy/app/releases/20150416231543/log ]
DEBUG [2f06f29a] Finished in 0.182 seconds with exit status 1 (failed).
DEBUG [6046b6f1] Running /usr/bin/env [ -d /home/deploy/app/releases/20150416231543/log ] as deploy@11.22.33.44
DEBUG [6046b6f1] Command: [ -d /home/deploy/app/releases/20150416231543/log ]
DEBUG [6046b6f1] Finished in 0.181 seconds with exit status 1 (failed).
INFO [dd81b005] Running /usr/bin/env ln -s /home/deploy/app/shared/log /home/deploy/app/releases/20150416231543/log as deploy@11.22.33.44
DEBUG [dd81b005] Command: /usr/bin/env ln -s /home/deploy/app/shared/log /home/deploy/app/releases/20150416231543/log
INFO [dd81b005] Finished in 0.178 seconds with exit status 0 (successful).
DEBUG [a72e96c9] Running /usr/bin/env [ -L /home/deploy/app/releases/20150416231543/tmp/pids ] as deploy@11.22.33.44
DEBUG [a72e96c9] Command: [ -L /home/deploy/app/releases/20150416231543/tmp/pids ]
DEBUG [a72e96c9] Finished in 0.183 seconds with exit status 1 (failed).
DEBUG [f0d3670c] Running /usr/bin/env [ -d /home/deploy/app/releases/20150416231543/tmp/pids ] as deploy@11.22.33.44
DEBUG [f0d3670c] Command: [ -d /home/deploy/app/releases/20150416231543/tmp/pids ]
DEBUG [f0d3670c] Finished in 0.180 seconds with exit status 1 (failed).
INFO [bf9e5b08] Running /usr/bin/env ln -s /home/deploy/app/shared/tmp/pids /home/deploy/app/releases/20150416231543/tmp/pids as deploy@11.22.33.44
DEBUG [bf9e5b08] Command: /usr/bin/env ln -s /home/deploy/app/shared/tmp/pids /home/deploy/app/releases/20150416231543/tmp/pids
INFO [bf9e5b08] Finished in 0.181 seconds with exit status 0 (successful).
DEBUG [7a6ffe80] Running /usr/bin/env [ -L /home/deploy/app/releases/20150416231543/tmp/cache ] as deploy@11.22.33.44
DEBUG [7a6ffe80] Command: [ -L /home/deploy/app/releases/20150416231543/tmp/cache ]
DEBUG [7a6ffe80] Finished in 0.179 seconds with exit status 1 (failed).
DEBUG [ce236154] Running /usr/bin/env [ -d /home/deploy/app/releases/20150416231543/tmp/cache ] as deploy@11.22.33.44
DEBUG [ce236154] Command: [ -d /home/deploy/app/releases/20150416231543/tmp/cache ]
DEBUG [ce236154] Finished in 0.175 seconds with exit status 1 (failed).
INFO [8ca88a51] Running /usr/bin/env ln -s /home/deploy/app/shared/tmp/cache /home/deploy/app/releases/20150416231543/tmp/cache as deploy@11.22.33.44
DEBUG [8ca88a51] Command: /usr/bin/env ln -s /home/deploy/app/shared/tmp/cache /home/deploy/app/releases/20150416231543/tmp/cache
INFO [8ca88a51] Finished in 0.181 seconds with exit status 0 (successful).
DEBUG [91b0d9a5] Running /usr/bin/env [ -L /home/deploy/app/releases/20150416231543/tmp/sockets ] as deploy@11.22.33.44
DEBUG [91b0d9a5] Command: [ -L /home/deploy/app/releases/20150416231543/tmp/sockets ]
DEBUG [91b0d9a5] Finished in 0.175 seconds with exit status 1 (failed).
DEBUG [e458c60b] Running /usr/bin/env [ -d /home/deploy/app/releases/20150416231543/tmp/sockets ] as deploy@11.22.33.44
DEBUG [e458c60b] Command: [ -d /home/deploy/app/releases/20150416231543/tmp/sockets ]
DEBUG [e458c60b] Finished in 0.179 seconds with exit status 1 (failed).
INFO [75700a48] Running /usr/bin/env ln -s /home/deploy/app/shared/tmp/sockets /home/deploy/app/releases/20150416231543/tmp/sockets as deploy@11.22.33.44
DEBUG [75700a48] Command: /usr/bin/env ln -s /home/deploy/app/shared/tmp/sockets /home/deploy/app/releases/20150416231543/tmp/sockets
INFO [75700a48] Finished in 0.186 seconds with exit status 0 (successful).
DEBUG [fc818abb] Running /usr/bin/env [ -L /home/deploy/app/releases/20150416231543/vendor/bundle ] as deploy@11.22.33.44
DEBUG [fc818abb] Command: [ -L /home/deploy/app/releases/20150416231543/vendor/bundle ]
DEBUG [fc818abb] Finished in 0.173 seconds with exit status 1 (failed).
DEBUG [b7e5f8a4] Running /usr/bin/env [ -d /home/deploy/app/releases/20150416231543/vendor/bundle ] as deploy@11.22.33.44
DEBUG [b7e5f8a4] Command: [ -d /home/deploy/app/releases/20150416231543/vendor/bundle ]
DEBUG [b7e5f8a4] Finished in 0.175 seconds with exit status 1 (failed).
INFO [cf69741a] Running /usr/bin/env ln -s /home/deploy/app/shared/vendor/bundle /home/deploy/app/releases/20150416231543/vendor/bundle as deploy@11.22.33.44
DEBUG [cf69741a] Command: /usr/bin/env ln -s /home/deploy/app/shared/vendor/bundle /home/deploy/app/releases/20150416231543/vendor/bundle
INFO [cf69741a] Finished in 0.188 seconds with exit status 0 (successful).
DEBUG [7c768481] Running /usr/bin/env [ -L /home/deploy/app/releases/20150416231543/public/system ] as deploy@11.22.33.44
DEBUG [7c768481] Command: [ -L /home/deploy/app/releases/20150416231543/public/system ]
DEBUG [7c768481] Finished in 0.178 seconds with exit status 1 (failed).
DEBUG [7393a52a] Running /usr/bin/env [ -d /home/deploy/app/releases/20150416231543/public/system ] as deploy@11.22.33.44
DEBUG [7393a52a] Command: [ -d /home/deploy/app/releases/20150416231543/public/system ]
DEBUG [7393a52a] Finished in 0.176 seconds with exit status 1 (failed).
INFO [b1ae7615] Running /usr/bin/env ln -s /home/deploy/app/shared/public/system /home/deploy/app/releases/20150416231543/public/system as deploy@11.22.33.44
DEBUG [b1ae7615] Command: /usr/bin/env ln -s /home/deploy/app/shared/public/system /home/deploy/app/releases/20150416231543/public/system
INFO [b1ae7615] Finished in 0.180 seconds with exit status 0 (successful).
DEBUG [0f939a7c] Running /usr/bin/env if test ! -d /home/deploy/app/releases/20150416231543; then echo "Directory does not exist '/home/deploy/app/releases/20150416231543'" 1>&2; false; fi as deploy@11.22.33.44
DEBUG [0f939a7c] Command: if test ! -d /home/deploy/app/releases/20150416231543; then echo "Directory does not exist '/home/deploy/app/releases/20150416231543'" 1>&2; false; fi
DEBUG [0f939a7c] Finished in 0.183 seconds with exit status 0 (successful).
INFO [d74e5ae8] Running /usr/local/bin/chruby-exec 2.2.1 -- bundle install --path /home/deploy/app/shared/bundle --without development test --deployment --quiet as deploy@11.22.33.44
DEBUG [d74e5ae8] Command: cd /home/deploy/app/releases/20150416231543 && /usr/local/bin/chruby-exec 2.2.1 -- bundle install --path /home/deploy/app/shared/bundle --without development test --deployment --quiet
INFO [d74e5ae8] Finished in 1.477 seconds with exit status 0 (successful).
DEBUG [9d19642a] Running /usr/bin/env if test ! -d /home/deploy/app/releases/20150416231543; then echo "Directory does not exist '/home/deploy/app/releases/20150416231543'" 1>&2; false; fi as deploy@11.22.33.44
DEBUG [9d19642a] Command: if test ! -d /home/deploy/app/releases/20150416231543; then echo "Directory does not exist '/home/deploy/app/releases/20150416231543'" 1>&2; false; fi
DEBUG [9d19642a] Finished in 0.175 seconds with exit status 0 (successful).
INFO [44e6dc78] Running /usr/local/bin/chruby-exec 2.2.1 -- bundle exec rake assets:precompile as deploy@11.22.33.44
DEBUG [44e6dc78] Command: cd /home/deploy/app/releases/20150416231543 && ( RAILS_ENV=production /usr/local/bin/chruby-exec 2.2.1 -- bundle exec rake assets:precompile )
DEBUG [44e6dc78] 	I, [2015-04-16T19:15:58.235749 #23282]  INFO -- : Writing /home/deploy/app/releases/20150416231543/public/assets/vendor/modernizr-8930220bcb710b239a9d4f592dd8d69ac02ed88ca245dc1a59caa99aaa6ec6ed.js
DEBUG [44e6dc78] 	I, [2015-04-16T19:15:59.064791 #23282]  INFO -- : Writing /home/deploy/app/releases/20150416231543/public/assets/application-52fe05489a3c31bd5b570261a6bdc19dee557282a83d169e5942ed6ccab124df.js
DEBUG [44e6dc78] 	I, [2015-04-16T19:16:08.152677 #23282]  INFO -- : Writing /home/deploy/app/releases/20150416231543/public/assets/application-8b79e2115a654c8f8569fc1776088424784cccd3de4452a7317f5bfe9154184d.css
DEBUG [44e6dc78] 	I, [2015-04-16T19:16:08.158878 #23282]  INFO -- : Writing /home/deploy/app/releases/20150416231543/public/assets/FontAwesome-bdc5d0b9f397be83e886c74b0141d1954aa4384b359dce49829994c4a2e1f7bf.otf
DEBUG [44e6dc78] 	I, [2015-04-16T19:16:08.160527 #23282]  INFO -- : Writing /home/deploy/app/releases/20150416231543/public/assets/fontawesome-webfont-cbb644d0ee730ea57dd5fbae35ef5ba4a41d57a254a6b1215de5c9ff8a321c2d.eot
DEBUG [44e6dc78] 	I, [2015-04-16T19:16:08.162015 #23282]  INFO -- : Writing /home/deploy/app/releases/20150416231543/public/assets/fontawesome-webfont-bfdef833219a6edffd9c3cbc28db72739d22bb4d20cc2e2f8d56a7a4d408a206.svg
DEBUG [44e6dc78] 	I, [2015-04-16T19:16:08.164434 #23282]  INFO -- : Writing /home/deploy/app/releases/20150416231543/public/assets/fontawesome-webfont-9e540a087924a6e64790149d735cac022640e4fa6bff6bd65f5e9f41529bf0b3.ttf
DEBUG [44e6dc78] 	I, [2015-04-16T19:16:08.165991 #23282]  INFO -- : Writing /home/deploy/app/releases/20150416231543/public/assets/fontawesome-webfont-e3870de89716b72cb61a4bba0e17c75783b361cdaba35ea96961c3070bd8ca18.woff
DEBUG [44e6dc78] 	I, [2015-04-16T19:16:08.167320 #23282]  INFO -- : Writing /home/deploy/app/releases/20150416231543/public/assets/fontawesome-webfont-aadc3580d2b64ff5a7e6f1425587db4e8b033efcbf8f5c332ca52a5ed580c87c.woff2
INFO [44e6dc78] Finished in 15.388 seconds with exit status 0 (successful).
DEBUG [9ece85d4] Running /usr/bin/env if test ! -d /home/deploy/app/releases/20150416231543; then echo "Directory does not exist '/home/deploy/app/releases/20150416231543'" 1>&2; false; fi as deploy@11.22.33.44
DEBUG [9ece85d4] Command: if test ! -d /home/deploy/app/releases/20150416231543; then echo "Directory does not exist '/home/deploy/app/releases/20150416231543'" 1>&2; false; fi
DEBUG [9ece85d4] Finished in 0.175 seconds with exit status 0 (successful).
INFO [396a06c9] Running /usr/bin/env cp /home/deploy/app/releases/20150416231543/public/assets/manifest* /home/deploy/app/releases/20150416231543/assets_manifest_backup as deploy@11.22.33.44
DEBUG [396a06c9] Command: cd /home/deploy/app/releases/20150416231543 && /usr/bin/env cp /home/deploy/app/releases/20150416231543/public/assets/manifest* /home/deploy/app/releases/20150416231543/assets_manifest_backup
DEBUG [396a06c9] 	cp:
DEBUG [396a06c9] 	cannot stat ‘/home/deploy/app/releases/20150416231543/public/assets/manifest*’
DEBUG [396a06c9] 	: No such file or directory
DEBUG [396a06c9]
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@11.22.33.44: cp exit status: 1
cp stdout: Nothing written
cp stderr: cp: cannot stat ‘/home/deploy/app/releases/20150416231543/public/assets/manifest*’: No such file or directory

SSHKit::Command::Failed: cp exit status: 1
cp stdout: Nothing written
cp stderr: cp: cannot stat ‘/home/deploy/app/releases/20150416231543/public/assets/manifest*’: No such file or directory

Tasks: TOP => deploy:assets:backup_manifest
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as deploy@11.22.33.44: cp exit status: 1
cp stdout: Nothing written
cp stderr: cp: cannot stat ‘/home/deploy/app/releases/20150416231543/public/assets/manifest*’: No such file or directory
```

**Comment by lessless** [comment]
any progress?

**Comment by kirs** [comment]
This is fixed in master.

**Comment by raskhadafi** [comment]
Had the same error that `ls .sprockets-manifest*` failed. 
It had to extend the command by `ls -a .sprockets-manifest*`

**Comment by alexander-lazarov** [comment]
The fix by lessless didn't work for me. The following (very ugly) code did the job, though. Do not use it if you're not sure what it actually does :)

```ruby
namespace :deploy do
  task :fix_absent_manifest_bug do
    on roles(:web) do
      within release_path do
        execute :rm, release_path.join('public', fetch(:assets_prefix), '.sprockets-manifest-*')
      end
   end
  end
```

**Comment by vysogot** [comment]
Still throwing on Rails 4.2.2, Ruby 2.2.2, sprockets 3.2.0, got to downgrade like the work around says, thanks.

**Comment by Mavvie** [comment]
Me too, with Rails 4.2, sprockets 3.3.3, ruby 2.2.2.

**Comment by bkazmer** [comment]
It failed when I upgraded rails 4.2 to 4.2.4. After I upgraded to capistrano-rails 1.1.3. and it works

**Comment by forever-ram** [comment]
I still got this issue. 

I've Rails 4.2.2 and Ruby 2.2.1
and capistrano-rails 1.1.3 and it installed sprockets 3.3.2 default
Do I still need to downgrade the sprockets version to 2.8?

**Comment by hw676018683** [comment]
@forever-ram with Rails 4.2.3 and Ruby 2.2.1, it works after upgrading capistrano-rails to 1.1.3 
maybe you upgrade Rails to 4.2.3

**Comment by crivotz** [comment]
Rails 4.2.4, it works after upgrading capistrano-rails to 1.1.3 and capistrano-bundler to 1.1.4

**Comment by alexey-klimuk** [comment]
@forever-ram I've noticed that error appears when there is some issues with linked_dirs
rails 4.2.4, capistrano-rails 1.1.3, capistrano-bundler 1.1.4

**Comment by taf2** [comment]
here's my fix

```
  task :fix_absent_manifest_bug do
    on roles(:web) do
      within release_path do  execute :mkdir,
        release_path.join('public', fetch(:assets_prefix))
      end

      within release_path do  execute :touch,
        release_path.join('public', fetch(:assets_prefix), 'manifest-fix.temp')
      end
    end
  end
  before :updated, 'deploy:fix_absent_manifest_bug'
```

I have it run before updated to create the assets directory and touch the manifest tmp file.   For me this was needed because the precompile runs prior to the after :updating event is triggered... it would be nice if by default Capistrano announced in the output that it's triggering X event... would make debugging much easier...

**Comment by toao** [comment]
Just run into this issue with capistrano-rails 1.1.5 and ruby 2.3.0, rails 4.2.5, sprockets 3.5.2

The fix from @lessless https://github.com/capistrano/rails/issues/111#issuecomment-94151119 worked for me, the one from @taf2 https://github.com/capistrano/rails/issues/111#issuecomment-167590766 didn't.

**Comment by stguitar** [comment]
@Tietew fix is working for me, I just locked my sprockets at '2.12.3'.

**Comment by lacco** [comment]
Updating to ```capistrano-rails 1.1.8``` fixed this issue for me.

**Comment by nextofsearch** [comment]
I have the same issue with Rails 3.2.22.5, ruby 1.9.3-p551, capistrano-rails 1.1.8 and sprockets 2.2.2

Here's my fix.

`
namespace :deploy do
 	task :fix_absent_manifest_bug do
    on roles(:web) do
      within release_path do  execute :touch,
        release_path.join('public', fetch(:assets_prefix), 'manifest.tmp')
      end
    end
  end
  before :updated, 'deploy:fix_absent_manifest_bug'
end

`

**Comment by kuzevanoff** [comment]
I have the same issue..


    cd /var/www/sa/releases/20170325010355 && /usr/bin/env cp /etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory /var/www/sa/releases/20170325010355/public/assets/.sprockets-manifest-3f843658ebd0a7e65891643e86a5bb23.json /var/www/sa/releases/20170325010355/assets_manifest_backup' cp stderr: Nothing written

My gems versions:

sprockets (3.7.1)
sprockets-rails (3.2.0)
capistrano-rails (1.2.3, 1.1.8) 
Rails 5.0.2
ruby 2.4.1
capistrano (3.8.0)
